// Product List
export const PRODUCT_LIST = 'PRODUCT_LIST';
export const PRODUCT_LIST_LOADING = 'PRODUCT_LIST_LOADING';
export const PRODUCT_LIST_ERROR = 'PRODUCT_LIST_ERROR';
export const PRODUCT_LIST_SUCESS = 'PRODUCT_LIST_SUCESS';

// Login 

export const LOGIN = "LOGIN";
export const LOGIN_SUCESS ="LOGIN_SUCESS"
export const LOGIN_EROOR="LOGIN_ERROR"
export const LOGIN_LOADING='LOGIN_LOADING'

// Register
export const REGISTER = "REGISTER";
export const REGISTER_SUCESS ="REGISTER_SUCESS"
export const REGISTER_EROOR="REGISTER_ERROR"
export const REGISTER_LOADING='REGISTER_LOADING'

//get categoeries List

export const CATEGOERIES_LIST="CATEGOERIES_LIST";
export const CATEGOERIES_LIST_SUCESS="CATEGOERIES_LIST_SUCESS";
export const CATEGOERIES_LIST_EROOR="CATEGOERIES_LIST_EROOR";
export const CATEGOERIES_LIST_LOADING="CATEGOERIES_LIST_LOADING";