// Product List
export const PRODUCT_LIST = 'PRODUCT_LIST';
export const PRODUCT_LIST_LOADING = 'PRODUCT_LIST_LOADING';
export const PRODUCT_LIST_ERROR = 'PRODUCT_LIST_ERROR';
export const PRODUCT_LIST_SUCESS = 'PRODUCT_LIST_SUCESS';

// Login 

export const LOGIN = "LOGIN";
export const LOGIN_SUCESS ="LOGIN_SUCESS"
export const LOGIN_EROOR="LOGIN_ERROR"
export const LOGIN_LOADING='LOGIN_LOADING'

// Register
export const REGISTER = "REGISTER";
export const REGISTER_SUCESS ="REGISTER_SUCESS"
export const REGISTER_EROOR="REGISTER_ERROR"
export const REGISTER_LOADING='REGISTER_LOADING'

//get categoeries List

export const CATEGOERIES_LIST="CATEGOERIES_LIST";
export const CATEGOERIES_LIST_SUCESS="CATEGOERIES_LIST_SUCESS";
export const CATEGOERIES_LIST_EROOR="CATEGOERIES_LIST_EROOR";
export const CATEGOERIES_LIST_LOADING="CATEGOERIES_LIST_LOADING";

//get Product CategoryBy Id
export const PRODUCT_LIST_BY_CAT_ID="PRODUCT_LIST_BY_CAT_ID";
export const PRODUCT_LIST_BY_CAT_ID_SUCESS="PRODUCT_LIST_BY_CAT_ID_SUCESS";
export const PRODUCT_LIST_BY_CAT_ID_EROOR="PRODUCT_LIST_BY_CAT_ID_EROOR";
export const PRODUCT_LIST_BY_CAT_ID_LOADING="PRODUCT_LIST_BY_CAT_ID_LOADING";

//Get Best Selling Product

export const GET_BEST_SELLING_PRODUCT="GET_BEST_SELLING_PRODUCT"
export const GET_BEST_SELLING_PRODUCT_SUCESS="GET_BEST_SELLING_PRODUCT_SUCESS"
export const GET_BEST_SELLING_PRODUCT_ERROR="GET_BEST_SELLING_PRODUCT_ERROR"
export const GET_BEST_SELLING_PRODUCT_LOADING="GET_BEST_SELLING_PRODUCT_LOADING"

//get Top Rated Product
export const GET_TOP_RATED_PRODUCT="GET_TOP_RATED_PRODUCT"
export const GET_TOP_RATED_PRODUCT_SUCESS="GET_TOP_RATED_PRODUCT_SUCESS"
export const GET_TOP_RATED_PRODUCT_ERROR="GET_TOP_RATED_PRODUCT_ERROR"
export const GET_TOP_RATED_PRODUCT_LOADING="GET_TOP_RATED_PRODUCT_LOADING"

//get Recent Produc
export const GET_RECENT_PRODUCT="GET_RECENT_PRODUCT"
export const GET_RECENT_PRODUCT_SUCESS="GET_RECENT_PRODUCT_SUCESS"
export const GET_RECENT_PRODUCT_ERROR="GET_RECENT_PRODUCT_ERROR"
export const GET_RECENT_PRODUCT_LOADING="GET_RECENT_PRODUCT_LOADING"

//Home Page

export const HOME_PAGE_DATA="HOME_PAGE_DATA"
export const HOME_PAGE_DATA_SUCESS="HOME_PAGE_DATA_SUCESS"
export const HOME_PAGE_DATA_ERROR="HOME_PAGE_DATA_ERROR"
export const HOME_PAGE_DATA_LOADING="HOME_PAGE_DATA_LOADING"

// Pincode

export const PINCODE ="PINCODE"
export const PINCODE_SUCESS ="PINCODE_SUCESS"
export const PINCODE_ERROR ="PINCODE_ERROR"
export const PINCODE_LOADING ="PINCODE_LOADING"

// get Featured Product

export const GET_FEATURED_PRODUCT="GET_FEATURED_PRODUCT"
export const GET_FEATURED_PRODUCT_SUCESS="GET_FEATURED_PRODUCT_SUCESS"
export const GET_FEATURED_PRODUCT_ERROR="GET_FEATURED_PRODUCT_ERROR"
export const GET_FEATURED_PRODUCT_LOADING="GET_FEATURED_PRODUCT_LOADING"

//onSale
export const GET_ON_SALE_PRODUCT="GET_ON_SALE_PRODUCT"
export const GET_ON_SALE_PRODUCT_SUCESS="GET_ON_SALE_PRODUCT_SUCESS"
export const GET_ON_SALE_PRODUCT_ERROR="GET_ON_SALE_PRODUCT_ERROR"
export const GET_ON_SALE_PRODUCT_LOADING="GET_ON_SALE_PRODUCT_LOADING"

//organic World

export const GET_ORGANIC_WORLD_PRODUCT="GET_ORGANIC_WORLD_PRODUCT"
export const  GET_ORGANIC_WORLD_PRODUCT_SUCESS="GET_ORGANIC_WORLD_PRODUCT_SUCESS"
export const  GET_ORGANIC_WORLD_PRODUCT_ERROR="GET_ORGANIC_WORLD_PRODUCT_ERROR"
export const  GET_ORGANIC_WORLD_PRODUCT_LOADING="GET_ORGANIC_WORLD_PRODUCT_LOADING"

// LogOut
export const LOG_OUT="LOG_OUT"
export const  LOG_OUT_SUCESS="LOG_OUT_SUCESS"
export const   LOG_OUT_ERROR="LOG_OUT_ERROR"
export const   LOG_OUT_LOADING=" LOG_OUT_LOADING"

//get Product By ID
export const PRODUCT_BY_ID = 'PRODUCT_BY_ID';
export const PRODUCT_BY_ID_LOADING = 'PRODUCT_BY_ID_LOADING';
export const PRODUCT_BY_ID_ERROR = 'PRODUCT_BY_ID_ERROR';
export const PRODUCT_BY_ID_SUCESS = 'PRODUCT_BY_ID_SUCESS';

//Best Offer

export const GET_BEST_OFFERS = 'GET_BEST_OFFERS';
export const GET_BEST_OFFERS_LOADING = 'GET_BEST_OFFERS_LOADING';
export const GET_BEST_OFFERS_ERROR = 'GET_BEST_OFFERS_ERROR';
export const GET_BEST_OFFERS_SUCESS = 'GET_BEST_OFFERS_SUCESS';

// Blogs

export const GET_BLOG_LIST = 'GET_BLOG_LIST';
export const GET_BLOG_LIST_LOADING = 'GET_BLOG_LIST_LOADING';
export const GET_BLOG_LIST_ERROR = 'GET_BLOG_LIST_ERROR';
export const GET_BLOG_LIST_SUCESS = 'GET_BLOG_LIST_SUCESS';

//keyword Product

export const PRODUCT_BY_KEYWORD = 'PRODUCT_BY_KEYWORD';
export const PRODUCT_BY_KEYWORD_LOADING = 'PRODUCT_BY_KEYWORD_LOADING';
export const PRODUCT_BY_KEYWORD_ERROR = 'PRODUCT_BY_KEYWORD_ERROR';
export const PRODUCT_BY_KEYWORD_SUCESS = 'PRODUCT_BY_KEYWORD_SUCESS';

//product Filter

export const PRODUCT_FILTER='PRODUCT_FILTER'
export const PRODUCT_FILTER_LOADING='PRODUCT_FILTER_LOADING'
export const PRODUCT_FILTER_SUCESS='PRODUCT_FILTER_SUCESS'
export const PRODUCT_FILTER_ERROR='PRODUCT_FILTER_ERROR'

//Videos

export const VIDEOS='VIDEOS'
export const VIDEOS_LOADING='VIDEOS_LOADING'
export const VIDEOS_SUCESS='VIDEOS_SUCESS'
export const VIDEOS_ERROR='VIDEOS_ERROR'

//Silder Banners

export const BANNERS='BANNERS'
export const BANNERS_LOADING='BANNERS_LOADING'
export const BANNERS_SUCESS='BANNERS_SUCESS'
export const BANNERS_ERROR='BANNERS_ERROR'

//Help

export const HELP='HELP'
export const HELP_LOADING='HELP_LOADING'
export const HELP_SUCESS='HELP_SUCESS'
export const HELP_ERROR='HELP_ERROR'

//add blog comment 

export const BLOG_COMMENT='BLOG_COMMENT'
export const BLOG_COMMENT_LOADING='BLOG_COMMENT_LOADING'
export const BLOG_COMMENT_SUCESS='BLOG_COMMENT_SUCESS'
export const BLOG_COMMENT_ERROR='BLOG_COMMENT_ERROR'

//getPRofile

export const GET_PROFILE='GET_PROFILE'
export const GET_PROFILE_LOADING='GET_PROFILE_LOADING'
export const GET_PROFILE_SUCESS='GET_PROFILE_SUCESS'
export const GET_PROFILE_ERROR='GET_PROFILE_ERROR'

//search Blog

export const BLOG_SEARCH='BLOG_SEARCH'
export const BLOG_SEARCH_SUCESS='BLOG_SEARCH_SUCESS'
export const BLOG_SEARCH_LOADING='BLOG_SEARCH_LOADING'
export const BLOG_SEARCH_ERROR='BLOG_SEARCH_ERROR'
