// Product List
export const PRODUCT_LIST = 'PRODUCT_LIST';
export const PRODUCT_LIST_LOADING = 'PRODUCT_LIST_LOADING';
export const PRODUCT_LIST_ERROR = 'PRODUCT_LIST_ERROR';
export const PRODUCT_LIST_SUCESS = 'PRODUCT_LIST_SUCESS';

// Login 

export const LOGIN = "LOGIN";
export const LOGIN_SUCESS ="LOGIN_SUCESS"
export const LOGIN_EROOR="LOGIN_ERROR"
export const LOGIN_LOADING='LOGIN_LOADING'

// Register
export const REGISTER = "REGISTER";
export const REGISTER_SUCESS ="REGISTER_SUCESS"
export const REGISTER_EROOR="REGISTER_ERROR"
export const REGISTER_LOADING='REGISTER_LOADING'

//get categoeries List

export const CATEGOERIES_LIST="CATEGOERIES_LIST";
export const CATEGOERIES_LIST_SUCESS="CATEGOERIES_LIST_SUCESS";
export const CATEGOERIES_LIST_EROOR="CATEGOERIES_LIST_EROOR";
export const CATEGOERIES_LIST_LOADING="CATEGOERIES_LIST_LOADING";

//get Product CategoryBy Id
export const PRODUCT_LIST_BY_CAT_ID="PRODUCT_LIST_BY_CAT_ID";
export const PRODUCT_LIST_BY_CAT_ID_SUCESS="PRODUCT_LIST_BY_CAT_ID_SUCESS";
export const PRODUCT_LIST_BY_CAT_ID_EROOR="PRODUCT_LIST_BY_CAT_ID_EROOR";
export const PRODUCT_LIST_BY_CAT_ID_LOADING="PRODUCT_LIST_BY_CAT_ID_LOADING";

//Get Best Selling Product

export const GET_BEST_SELLING_PRODUCT="GET_BEST_SELLING_PRODUCT"
export const GET_BEST_SELLING_PRODUCT_SUCESS="GET_BEST_SELLING_PRODUCT_SUCESS"
export const GET_BEST_SELLING_PRODUCT_ERROR="GET_BEST_SELLING_PRODUCT_ERROR"
export const GET_BEST_SELLING_PRODUCT_LOADING="GET_BEST_SELLING_PRODUCT_LOADING"

//get Top Rated Product
export const GET_TOP_RATED_PRODUCT="GET_TOP_RATED_PRODUCT"
export const GET_TOP_RATED_PRODUCT_SUCESS="GET_TOP_RATED_PRODUCT_SUCESS"
export const GET_TOP_RATED_PRODUCT_ERROR="GET_TOP_RATED_PRODUCT_ERROR"
export const GET_TOP_RATED_PRODUCT_LOADING="GET_TOP_RATED_PRODUCT_LOADING"

//get Recent Produc
export const GET_RECENT_PRODUCT="GET_RECENT_PRODUCT"
export const GET_RECENT_PRODUCT_SUCESS="GET_RECENT_PRODUCT_SUCESS"
export const GET_RECENT_PRODUCT_ERROR="GET_RECENT_PRODUCT_ERROR"
export const GET_RECENT_PRODUCT_LOADING="GET_RECENT_PRODUCT_LOADING"